version: "3.9"

services:
  # === Base de données PostgreSQL ===
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password_change_me}
      POSTGRES_USER: ${DB_USER:-cipfaro}
      POSTGRES_DB: ${DB_NAME:-cipfaro_production}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cipfaro-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-cipfaro}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # === Redis Cache ===
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - cipfaro-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  cipfaro-network:
    driver: bridge