global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # API Express metrics
  - job_name: "api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:4000"]

  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # MinIO metrics (if enabled)
  - job_name: "minio"
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]